from fpdf import FPDF
import io
import re

class RecipePDF(FPDF):
    """Custom PDF class for recipe generation"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.set_margins(15, 15, 15)  
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # The header is intentionally left blank to avoid repeated headings.
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'Generated by Dishcovery - Powered by Google Gemini AI', 0, 0, 'C')

def generate_pdf(recipe_text: str) -> bytes:
    """Generate a professional, clean PDF document from the recipe text. Only the recipe name appears as a bold heading at the top of the first page. All content is plain, well-structured, and without special symbols or colors."""
    try:
        pdf = RecipePDF(orientation='P', unit='mm', format='A4')
        pdf.set_margins(20, 20, 20)
        pdf.add_page()

        # Extracts the recipe name as the first non-empty line
        lines = recipe_text.strip().split('\n')
        recipe_name = ''
        content_lines = []
        for line in lines:
            if recipe_name == '' and line.strip():
                recipe_name = line.strip().strip('#').strip()
            else:
                content_lines.append(line)

        # Adds generated recipe name as heading 
        pdf.set_font('Helvetica', 'B', 18)
        pdf.cell(0, 14, recipe_name, 0, 1, 'C')
        pdf.ln(6)
        pdf.set_font('Helvetica', '', 12)

        # Well-Strcuture Content
        for line in content_lines:
            stripped = line.strip()
            if not stripped:
                pdf.ln(2)
                continue
            # Bold labels
            bold_label_match = re.match(r'^\*\*(.+?):\*\*\s*(.*)$', stripped)
            if bold_label_match:
                label = bold_label_match.group(1).strip()
                value = bold_label_match.group(2).strip()
                pdf.set_left_margin(20)
                pdf.set_font('Helvetica', 'B', 12)
                label_width = pdf.get_string_width(label + ': ')
                pdf.cell(label_width, 7, label + ':', 0, 0)
                pdf.set_font('Helvetica', '', 12)
                # Use multi_cell for value so it wraps
                x = pdf.get_x()
                y = pdf.get_y()
                pdf.set_xy(x, y)
                pdf.multi_cell(0, 7, value)
                continue
            # Treat lines with only uppercase as section headings
            if stripped.isupper():
                pdf.ln(3)
                pdf.set_font('Helvetica', 'B', 13)
                pdf.cell(0, 9, stripped, 0, 1)
                pdf.set_font('Helvetica', '', 12)
                pdf.ln(1)
            # Treat lines starting with a number as steps
            elif re.match(r'^\d+\.', stripped):
                pdf.set_left_margin(28)
                pdf.cell(8, 7, '', 0, 0)  # Indent
                pdf.multi_cell(0, 7, stripped)
                pdf.set_left_margin(20)
            else:
                pdf.set_left_margin(20)
                pdf.multi_cell(0, 7, stripped)

        return pdf.output(dest='S').encode('latin-1')
    except Exception as e:
        pdf = FPDF(orientation='P', unit='mm', format='A4')
        pdf.add_page()
        pdf.set_font('Helvetica', '', 12)
        pdf.multi_cell(0, 10, f'Error generating PDF: {str(e)}\n\nPlease try again.')
        return pdf.output(dest='S').encode('latin-1')
